### ISSUE TITLE
TODO: __str__ formatting 

### ISSUE THREAD

**Issue by BlairDHall** [MSLNZ/GTC#1]
`__str__` formatting
=============
This version of GTC formats uncertain numbers as strings (the __str__ method) by using a fixed point format. The number of significant digits used is sufficient to display the standard uncertainty to 2 significant figures. The standard uncertainty is appended inside parentheses. For example, if we have `x = ureal(math.pi,0.001)` then `print x` will display ``3.1416(10)``   

It would be good to extend this behaviour to handle scientific notation as well, so that if the value of an uncertain number would normally be displayed in scientific notation by Python's print, then our uncertain number will use that format too. 

This will require some thought!

At the same time, we should consider and implementation of `__format__`, so that users can have some control of the display. We may need/prefer our own API functions in addition to/instead of  `__format__`

**Comment by jborbely** [comment]
Fixed in version 1.4.0.

The `__format__` method was overrided and the `create_format`, `apply_format` and `to_string` functions were added.
