### ISSUE TITLE
should is_infinity and is_undefined handle uncertain numbers?

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/GTC#11]
Should the following example raise a `TypeError` or return a `bool`?
```python
>>> from GTC import ureal, is_infinity, is_undefined
>>> a = ureal(1, 0.1)
>>> is_infinity(a)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: must be real number, not UncertainReal
>>> is_undefined(a)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: must be real number, not UncertainReal
```
I'm leaning more towards supporting this feature and return a `bool`.

Would it be useful for `is_infinity` to differentiate between -INF and +INF? Perhaps by accepting a `kwarg` or by implementing two different functions `is_negative_infinity`, `is_positive_infinity`.

**Comment by BlairDHall** [comment]
`is_infinity` and `is_undefined` are used exclusively with a degrees of
freedom parameter. Degrees of freedom are never negative.

**Comment by jborbely** [comment]
I agree that they are internally used for DOF. For the public API, is there a reason why theses functions should not support uncertain numbers? Should we create new public functions that are designed for these cases?

While creating a unit test for the `UncertainArray` class I got this unexpected `TypeError` when I was expecting a `bool` to be returned. So, I've already come across a situation where a, for example, _is_positive_infinity_ function would be useful.

**Comment by BlairDHall** [comment]
What was the situation you encountered?

**Comment by jborbely** [comment]
I was testing element-wise comparisons for the `UncertainArray` implementation of the [minimum](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.minimum.html) ufunc and I was curious what the result would be if an element in the `UncertainArray` became INF or NaN during a calculation.

I used the `is_infinity` and `is_undefined` functions in my implementation.

However, if I didn't use these functions and chose to use a more-pythonic implementation
```python
>>> ureal(inf, 0) > ureal(1, 0)
True
>>> ureal(inf, 0) < ureal(1, 0)
False
>>> ureal(-inf, 0) < ureal(1, 0)
True
>>> ureal(-inf, 0) < ureal(nan, 0)
False
>>> ureal(inf, 0) > ureal(nan, 0)
False
>>> ureal(inf, 0) >= inf
True
```
then I would have received the expected value.

So, I guess that my question could be rephrased to: Should `is_infinity` be renamed to `_is_infinity` or what do we think a user might attempt to use `is_infinity` for in their own code?

**Comment by BlairDHall** [comment]
Yes, I think to make the function private is a fair suggestion.

**Comment by jborbely** [comment]
I'd also suggest that we decide if any of the other constants defined in `__init__.py` should be considered as private.

**Comment by BlairDHall** [comment]
I have made some changes along these lines to __init__.py in the latest
commit.

**Comment by BlairDHall** [comment]
`is_infinity` and `is_undefined` have been replaced by their math. implementations. So this issue is closed
