### ISSUE TITLE
Python 2 vs 3 handle (-1.0)**(0.5) differently

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/GTC#13]
Python 2 and 3 have different outcomes when [this](https://github.com/MSLNZ/GTC/blob/dce03abfe92b5460229b52628c41f664dbfc8dc5/test/test_uncertain_real.py#L963) line is executed in the tests and the issue relates to how the line [y = l**r](https://github.com/MSLNZ/GTC/blob/dce03abfe92b5460229b52628c41f664dbfc8dc5/GTC/lib.py#L1095) in the `lib._pow` function handles the calculation.

The inputs to the `__pow__` method for this test are: 
self.un3 = lhs = -1.00(40)
self.un2 = rhs = 0.50(40)

**Outcome for Python 2.7**
```python
y = (-1.0)**(0.5)  # y = l**r
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: negative number cannot be raised to a fractional power
```
**Outcome for Python 3.x**
```python
y = (-1.0)**(0.5)  # y = l**r
(6.123233995736766e-17+1j)
```
So, the test in Python 2 expects that a `ValueError` is raised, however, this does not occur in Python 3. In Python 3 the value `(6.123233995736766e-17+1j)` gets passed to `UncertainReal.__init__` which raises a `TypeError` and then the test fails in Python 3.x:
```python
self._x = float(6.123233995736766e-17+1j)  # self._x = float(x)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: can't convert complex to float
```
Regardless of the version of Python, creating a new `UncertainReal` from the calculation (-1.0)**(0.5) raises an exception.

**Comment by BlairDHall** [comment]
The py2 case can be addressed by catching the ValueError exception and
creating a complex uncertain, or just complex number (depending on the
case), before executing lsh**rhs again, which will call the complex
implementation of _pow

The py3 case could be handled by looking at the type of number returned by
l**r (value calculation). If it is complex, then we set up the complex
problem again and call the complex implementation of _pow.

How does that sound?

**Comment by jborbely** [comment]
Sounds good to me

**Comment by BlairDHall** [comment]
These changes have been made and committed to the develop branch
