### ISSUE TITLE
type_a functions do not support uncertain numbers

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/GTC#15]
According to our docs the functions in the `type_a` module support receiving a sequence of uncertain numbers. However, the following fails
```python
>>> x = [ureal(1, 1), ureal(2, 2), ureal(3, 3)]
>>> type_a.mean(x)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\code\git\GTC\GTC\type_a.py", line 250, in mean
    return float(mu)
TypeError: float() argument must be a string or a number, not 'UncertainReal'
```
I'm not sure if the intention was for these functions to support uncertain numbers but we haven't got around to changing the code or if the docs should specify that only sequences of type `numbers.Real` or `numbers.Complex` are supported. The docs do say _Many functions in type_a treat data as pure numbers_ so should we restrict to only  pass in _pure numbers_?

**Comment by BlairDHall** [comment]
The intention is to support uncertain numbers. The `float` of mu needs to
be changed to `value`. This is a hangover from the previous version where
float and complex were able to cast uncertain numbers to their values.

I will fix this.

Should write a test case too!


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
