### ISSUE TITLE
Inverse matrix

### ISSUE THREAD

**Issue by PeterPirog** [MSLNZ/GTC#18]
Is possibile to make inverse matrix from 2D-UncertainArray?
I try use GTC.la.inv(A) where A is 2D-UncertainArray type , but i have the error:

  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\GTC\linear_algebra.py", line 294, in inv
    return LU.invab(a,np.identity(a.shape[0]))
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\GTC\LU.py", line 192, in invab
    y[i,j] = col[i]
TypeError: float() argument must be a string or a number, not 'UncertainReal'

**Comment by BlairDHall** [comment]
To calculate the inverse, use the `inv()` function [see the docs](https://gtc.readthedocs.io/en/stable/API/linear_algebra.html#linear_algebra.inv)

**Comment by PeterPirog** [comment]
As a RF engineer I appreciate Your huge effort to do this uncertainty library.
I try to expand some function, however i have problem with inverted matrix, my goal is to do function to calculate pseudoinverse matrix.

Below here is code which generate error:
[https://github.com/PeterPirog/PRT_calculations/blob/master/example01.py](url)

Errors:
  File "C:/Users/Przemek/PycharmProjects/PRT_calculations/example01.py", line 88, in <module>
    print('\n',GTC.la.inv(unc_array))     # <<<<<-------------------  ERROR
  File "C:\Users\Przemek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\GTC\linear_algebra.py", line 294, in inv
    return LU.invab(a,np.identity(a.shape[0]))
  File "C:\Users\Przemek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\GTC\LU.py", line 192, in invab
    y[i,j] = col[i]
TypeError: float() argument must be a string or a number, not 'UncertainReal'

**Comment by BlairDHall** [comment]
Yes, it appears there is a bug. We will follow up as soon as possible.

You can try the following patch, if you like:

In the file `linear_algebra.py`, replace the body of the function `inv()` with these two lines:

    b = np.identity(a.shape[0],a.dtype)
    return LU.invab(a,b)

If this works for you, please let us know.

**Comment by PeterPirog** [comment]
It works very well, now I can calculate pseudoinverse matrix :)

**Comment by BlairDHall** [comment]
I don't think you have provided an example that can be expected to work. I have implemented the following, based on your previous post:

    def np_pinv(uncertainty_array):
        # A+=(AtxA)^1 x At
        A = uncertainty_array
        At =A.T
        AtA=np.matmul(At,A)
        invAtA=np.linalg.inv(AtA)
        return np.matmul(invAtA,At)

And then executed the following 

    M=np.array([[1,2,3],[3,4,5]])
    inv_M=np_pinv(M)
    print('inv_M=\n',inv_M)

This also produces your error message 

    File "C:\Python27\lib\site-packages\numpy\linalg\linalg.py", line 551, in inv 
        ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
    File "C:\Python27\lib\site-packages\numpy\linalg\linalg.py", line 97, in _raise_linalgerror_singular
        raise LinAlgError("Singular matrix")
    numpy.linalg.LinAlgError: Singular matrix

So, I don't think this is our issue.

**Comment by PeterPirog** [comment]
Thank You, I will  test pseudoinverse matrix in numpy

**Comment by BlairDHall** [comment]
Closing this now, because release v1.2.1 has patched this bug.
