### ISSUE TITLE
ZeroDivisionError in reporting.sensitivity()

### ISSUE THREAD

**Issue by JensReimann** [MSLNZ/GTC#20]
Dear Blair,
reporting.sensitivity() raises ZeroDivisionError for UncertaintyComplex if any single part (real or imaginary) is zero, e.g. both value are actually real and their imaginary part is zero.

reporting.sensitivity() should be more tollerant and return a JacobianMatrix with some components set to "inf" in this case.

Thanks.

**Comment by BlairDHall** [comment]
Thank you Jens, we agree that this method can probably be improved, or at least it can be better documented. We will investigate. 

Note that when the real or imaginary component of a complex term is absent from a mathematical expression, the corresponding (analytic) derivative is zero (does not exist), not infinity. GTC handles this correctly, I think, but if an uncertain number is assigned an uncertainty of zero the case is not treated in the same way. 

We will not be able to make `reporting.sensitvity()` return the value of a partial derivative that has been weighted by a zero standard uncertainty in the measurement model. 

So, if you need to evalute partial derivatives, not components of uncertainty, you should assign all the input standard uncertainties to unity.

**Comment by BlairDHall** [comment]
Dear Jens, The latest release (1.3.8) has addressed this issue. 

As noted above, the correct sensitivity response when a component is not uncertain should be zero. 

Thank you for bring this to our attention.
