### ISSUE TITLE
Unresolved reference 're' and 'im' in willink_hall()

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/GTC#9]
The local parameters 're' and 'im' are not defined in the `lib_complex.willink_hall()` function.

These parameters are used within this section of code (in particular, lines 2039 and 2040 in the current version of `lib_complex.py` in the _develop_ branch)
```python
                    # If we can get here, this real influence can be
                    # used for the DoF calculation. 
                    # Update the buffer. 
                    if not i_re_infinite:
                        components_i.u_re.append( id_re,re[id_re] )  # undefined 're' parameter
                        components_i.u_im.append( id_re,im[id_re] )  # undefined 'im' parameter
```

**Comment by BlairDHall** [comment]
Have corrected the source code, but we need to extend our test cases to over this.

**Comment by BlairDHall** [comment]
This has been addressed now and recent additions to the test suite now cover these lines of code.
